//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyfendryAcademyWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursePlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoursePlan()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public Nullable<long> CourseId { get; set; }
        public string StripePriceId { get; set; }
        public Nullable<decimal> UpFrontPrice { get; set; }
        public Nullable<decimal> PlanPrice { get; set; }
        public string Interval { get; set; }
        public Nullable<int> IntervalValue { get; set; }
    
        public virtual Cours Cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
