//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyfendryAcademyWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long Id { get; set; }
        public Nullable<long> UserCourseId { get; set; }
        public Nullable<int> CoursePlanId { get; set; }
        public string StripeSessionId { get; set; }
        public string StripePaymentIntentId { get; set; }
        public string StripeSubscriptionId { get; set; }
        public string StripePaymentId { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual CoursePlan CoursePlan { get; set; }
        public virtual UserCours UserCours { get; set; }
    }
}
